<?xml version="1.0"?>
<package format="3">
  <name>rgbd_tf_publisher</name>
  <version>0.0.1</version>
  <description>Publishes a static transform between base_link and camera_link.</description>
  <maintainer email="magic.global.k@gmail.com">Spadeyache</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
