<?xml version="1.0"?>
<package format="3">
  <name>tf2_addon</name>
  <version>0.1.0</version>
  <description>Static TF2 broadcaster in C++</description>
  <maintainer email="your@email.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>geometry_msgs</depend>
</package>
